use_frameworks!

platform :ios, '8.0'

target 'LNBaseComponent_Example' do
  pod 'LNBaseComponent', :path => '../'
  pod 'WebViewJavascriptBridge', '~> 6.0.3'

  target 'LNBaseComponent_Tests' do
    inherit! :search_paths

  end
end
